#include <limits.h>
#include <stdio.h>
#include "main.h"

/**
 * main - Entry point
 *
 * Return: Always 0
 */
int main(void)
{
	char* str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. In posuere, turpis ut consequat gravida, urna dui consequat massa, sit amet varius nibh mauris vitae velit. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nullam eu dignissim elit. Aliquam suscipit quam et semper elementum. Vivamus pellentesque, nisl euismod lacinia convallis, tellus leo aliquam mauris, a convallis dui sapien vitae arcu. Donec pharetra velit a leo gravida ultricies. Aliquam erat vel.";
	long int lo;

_printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
printf("\n");
_printf("%");
printf("%");
printf("\n");
printf("INT MIN :");
_printf("%d", INT_MIN);
printf("\n");
printf("%d", INT_MIN);
printf("\n");
_printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("\n");
_printf("%i", 1024);
printf("%i", 1024);
printf("\n");
_printf("%i", -1024);
printf("%i", -1024);
printf("\n");
_printf("%i", 0);
printf("%i", 0);
printf("\n");
_printf("%i", INT_MAX);
printf("%i", INT_MAX);
printf("\n");
_printf("%i", INT_MIN);
printf("%i", INT_MIN);
printf("\n");
lo = INT_MAX - 1024;
_printf("%i", lo);
printf("%i", lo);
printf("\n");
_printf("There is %i bytes in %i KB\n", 1024, 1);
printf("There is %i bytes in %i KB\n", 1024, 1);
printf("\n");
_printf("%i - %i = %i\n", 1024, 2048, -1024);
printf("%i - %i = %i\n", 1024, 2048, -1024);
printf("\n");
_printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("\n");
_printf("%d == %i\n", 1024, 1024);
printf("%d == %i\n", 1024, 1024);
printf("\n");
_printf("iddi%diddiiddi\n", 1025);
printf("iddi%diddiiddi\n", 1024);
printf("\n");
_printf("%d", 10000);
printf("%d", 10000);
printf("\n");
_printf("%i", 10000);
printf("%i", 10000);_printf("Let's print a simple sentence.\n");
printf("Let's print a simple sentence.\n");
printf("\n");
_printf("%c", 'S');
printf("%c", 'S');
printf("\n");
_printf("A char inside a sentence: %c. Did it work?\n", 'F');
printf("A char inside a sentence: %c. Did it work?\n", 'F');
printf("\n");
_printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
printf("Let'see if the cast is correctly done: %c. Did it work?\n", 48);
printf("\n");
_printf("%s", "This sentence is retrieved from va_args!\n");
printf("%s", "This sentence is retrieved from va_args!\n");
printf("\n");
_printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
printf("Complete the sentence: You %s nothing, Jon Snow.\n", "know");
printf("\n");
_printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
printf("Complete the sentence: You %s nothing, Jon Snow.\n", (char *)0);
printf("\n");
_printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
printf("%c%cth %s%s a%cg%s: Y%sou %s no%ching%s Snow.%c", 'W', 'i', "some ", "more", 'r', "s", "", "know", 't', ", Jon", '\n');
printf("\n");
_printf("%%");
printf("%%");
printf("\n");
_printf("Should print a single percent sign: %%\n");
printf("Should print a single percent sign: %%\n");
printf("\n");
_printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
printf("%s%c%c%c%s%%%s%c", "Loading ", '.', '.', '.', " 99", " Please wait", '\n');
printf("\n");
_printf("css%ccs%scscscs", 'T', "Test");
printf("css%ccs%scscscs", 'T', "Test");
printf("\n");
_printf(str);
printf(str);
printf("\n");
_printf("man gcc:\n%s", str);
printf("man gcc:\n%s", str);
printf("\n");
_printf(NULL);
printf(NULL);
printf("\n");
_printf("%c", '\0');
printf("%c", '\0');
printf("\n");
_printf("%");
printf("%");
printf("\n");
_printf("%!\n");
printf("%!\n");
printf("\n");
_printf("%K\n");
printf("%K\n");
printf("\n");
_printf("%d", 1024);
printf("%d", 1024);
printf("\n");
_printf("%d", -1024);
printf("%d", -1024);
printf("\n");
_printf("%d", 0);
printf("%d", 0);
printf("\n");
_printf("%d", INT_MAX);
printf("%d", INT_MAX);
printf("\n");
_printf("%d", INT_MIN);
printf("%d", INT_MIN);
printf("\n");
lo = INT_MAX - 1024;
_printf("%d", lo);
printf("%d", lo);
printf("\n");
_printf("There is %d bytes in %d KB\n", 1024, 1);
printf("There is %d bytes in %d KB\n", 1024, 1);
printf("\n");
_printf("%d - %d = %d\n", 1024, 2048, -1024);
printf("%d - %d = %d\n", 1024, 2048, -1024);
printf("\n");
_printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("%d + %d = %d\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("\n");
_printf("%i", 1024);
printf("%i", 1024);
printf("\n");
_printf("%i", -1024);
printf("%i", -1024);
printf("\n");
_printf("%i", 0);
printf("%i", 0);
printf("\n");
_printf("%i", INT_MAX);
printf("%i", INT_MAX);
printf("\n");
_printf("%i", INT_MIN);
printf("%i", INT_MIN);
printf("\n");
lo = INT_MAX - 1024;
_printf("%i", lo);
printf("%i", lo);
printf("\n");
_printf("There is %i bytes in %i KB\n", 1024, 1);
printf("There is %i bytes in %i KB\n", 1024, 1);
printf("\n");
_printf("%i - %i = %i\n", 1024, 2048, -1024);
printf("%i - %i = %i\n", 1024, 2048, -1024);
printf("\n");
_printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("%i + %i = %i\n", INT_MIN, INT_MAX, (INT_MIN + INT_MAX));
printf("\n");
_printf("%d == %i\n", 1024, 1024);
printf("%d == %i\n", 1024, 1024);
printf("\n");
_printf("iddi%diddiiddi\n", 1024);
printf("iddi%diddiiddi\n", 1024);
printf("\n");
_printf("%d", 10000);
printf("%d", 10000);
printf("\n");
_printf("%i", 10000);
printf("%i", 10000);


/**
 * lo = INT_MAX + 1024;
_printf("%i",lo);
printf("%i", lo);
printf("\n");

_printf("%d", lo);
printf("%d", lo);
printf("\n");
*/
    return (0);
}
